pull_request_rules:
  - name: Automatically merge on CI success and review approval
    conditions:
      - base=master
      - approved-reviews-by=clareliguori
      - status-success=Build Image
      - author!=dependabot[bot]
    actions:
      merge:
        method: squash
        strict: smart
        strict_method: merge

  - name: Automatically merge Dependabot PRs
    actions:
      review:
        type: APPROVE
      merge:
        method: squash
        strict: smart+fasttrack
        strict_method: merge
    conditions:
      - base=master
      - author=dependabot[bot]
      - label=dependencies
      - status-success=Build Image
